services:
  lint:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /app
    environment:
      - CARGO_HOME=/usr/local/cargo
    command: |
      sh -c "
        rustup component list --installed &&
        cargo fmt --version &&
        cargo clippy --version &&
        cargo fmt --check &&
        cargo clippy -- -D warnings &&
        cargo check
      "

  test:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /app
    environment:
      - RUST_LOG=error
      - CI=true
    command: |
      sh -c "
        cargo test --release --verbose
      "

  build-release:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - ./artifacts:/artifacts
    working_dir: /app
    command: |
      sh -c "
        cargo build --release &&
        cp target/release/opencli /artifacts/ &&
        strip /artifacts/opencli
      "

  security-audit:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /app
    command: |
      sh -c "
        cargo install cargo-audit &&
        cargo audit
      "

  integration-test:
    build:
      context: .
      target: runtime
    volumes:
      - opencli-config:/home/opencli/.config/opencli
    user: opencli
    working_dir: /home/opencli
    entrypoint: ["sh"]
    environment:
      - HOME=/home/opencli
      - USER=opencli
    command: |
      -c "
        echo 'main() {}' > gamemode.pwn &&
        opencli setup --force &&
        opencli install compiler &&
        opencli package install Y-Less/sscanf --target components &&
        opencli build --verbose &&
        opencli package list
      "

  benchmark:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /app
    command: cargo bench

volumes:
  cargo-cache:
  opencli-config:
