services:
  lint:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CARGO_HOME=/app/.cargo
      - CARGO_TARGET_DIR=/app/target
    command: |
      sh -c "
        cargo fmt --check &&
        cargo clippy --no-deps -- -D warnings &&
        cargo check
      "

  test:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - RUST_LOG=error
      - CI=true
      - CARGO_HOME=/app/.cargo
      - CARGO_TARGET_DIR=/app/target
    depends_on:
      - lint
    command: |
      sh -c "
        cargo test --release
      "

  build-release:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - ./artifacts:/artifacts
    working_dir: /app
    environment:
      - CARGO_HOME=/app/.cargo
      - CARGO_TARGET_DIR=/app/target
    depends_on:
      - test
    command: |
      sh -c "
        cargo build --release &&
        mkdir -p /artifacts &&
        cp target/release/opencli /artifacts/
      "

  security-audit:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CARGO_HOME=/app/.cargo-audit
      - CARGO_TARGET_DIR=/app/target-audit
    depends_on:
      - build-release
    command: |
      sh -c "
        cargo install cargo-audit &&
        cargo audit
      "

  integration-test:
    build:
      context: .
      target: runtime
    volumes:
      - opencli-config:/home/opencli/.config/opencli
    user: opencli
    working_dir: /home/opencli
    entrypoint: ["sh"]
    environment:
      - HOME=/home/opencli
      - USER=opencli
    depends_on:
      - security-audit
    command: |
      -c "
        echo 'main() {}' > gamemode.pwn &&
        opencli setup --force &&
        opencli install compiler &&
        opencli package install Y-Less/sscanf --target components &&
        opencli build --verbose &&
        opencli package list &&
        opencli package check
      "

volumes:
  opencli-config:
