services:
  lint:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CARGO_HOME=/tmp/cargo-lint
      - CARGO_TARGET_DIR=/tmp/target-lint
    command: |
      sh -c "
        echo '=== Lint Stage ===' &&
        rustup component list --installed &&
        echo 'Running cargo fmt check...' &&
        cargo fmt --check &&
        echo 'Running cargo clippy...' &&
        cargo clippy --no-deps -- -D warnings &&
        echo 'Running cargo check...' &&
        cargo check &&
        echo 'Lint stage completed successfully!'
      "

  test:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - RUST_LOG=error
      - CI=true
      - CARGO_HOME=/tmp/cargo-test
      - CARGO_TARGET_DIR=/tmp/target-test
    depends_on:
      lint:
        condition: service_completed_successfully
    command: |
      sh -c "
        echo '=== Test Stage ===' &&
        cargo test --release &&
        echo 'Test stage completed successfully!'
      "

  build:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - ./artifacts:/artifacts
    working_dir: /app
    environment:
      - CARGO_HOME=/tmp/cargo-build
      - CARGO_TARGET_DIR=/tmp/target-build
    depends_on:
      test:
        condition: service_completed_successfully
    command: |
      sh -c "
        echo '=== Build Stage ===' &&
        cargo build --release &&
        mkdir -p /artifacts &&
        cp /tmp/target-build/release/opencli /artifacts/ &&
        strip /artifacts/opencli &&
        echo 'Build stage completed successfully!'
      "

  integration:
    build:
      context: .
      target: runtime
    volumes:
      - opencli-config:/home/opencli/.config/opencli
    user: opencli
    working_dir: /home/opencli
    entrypoint: ["sh"]
    environment:
      - HOME=/home/opencli
      - USER=opencli
    depends_on:
      build:
        condition: service_completed_successfully
    command: |
      -c "
        echo '=== Integration Test Stage ===' &&
        echo 'main() {}' > gamemode.pwn &&
        opencli setup --force &&
        opencli install compiler &&
        opencli package install Y-Less/sscanf --target components &&
        opencli build --verbose &&
        opencli package list &&
        echo 'Integration test completed successfully!'
      "

volumes:
  opencli-config:
